<div class="d-flex flex-row">
	<div
		class="card"
		style="width: 15rem">
		<img
			class="card-img-top p-5"
			src="images/bandaid-fill.svg"
			alt="Card image cap" />
		<div class="card-body">
			<a
				href="services/list"
				class="btn btn-primary btn-lg btn-block w-100"
				>Serviços</a
			>
		</div>
	</div>
	
	<div
		class="card"
		style="width: 15rem">
		<img
			class="card-img-top p-5"
			src="images/basket2-fill.svg"
			alt="Card image cap" />
	
		<div class="card-body">
			<a
				href="sales/list"
				class="btn btn-primary btn-lg btn-block w-100"
				>Promoções</a
			>
		</div>
	</div>
</div>
