
</div>
		</main>
		<footer
		class="container d-flex flex-column flex-sm-row justify-content-between py-4 border-top">
		<a
			href="https://mpftavares.github.io/farm_patuleia/#/home"
			target="_blank">
			<img
				class="logo"
				src="/images/logo.svg"
				alt="logo" />
		</a>

		<ul class="list-unstyled d-flex justify-content-between">
			<li>&copy; 2023 mpftavares</li>
			<li class="ms-3">
				<a
					class="link-body-emphasis"
					href="https://instagram.com/mpftavares"
					target="_blank">
					<i class="bi bi-instagram"></i>
				</a>
			</li>
			<li class="ms-3">
				<a
					class="link-body-emphasis"
					href="https://github.com/mpftavares"
					target="_blank">
					<i class="bi bi-github"></i>
				</a>
			</li>
		</ul>
	</footer>

		<script
			src="https://getbootstrap.com/docs/5.3/dist/js/bootstrap.bundle.min.js"
			integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
			crossorigin="anonymous"></script>  
	</body>
</html>