<!DOCTYPE html>
<html
	lang="en"
	data-bs-theme="auto">
	<head>
		<script src="https://getbootstrap.com/docs/5.3/assets/js/color-modes.js"></script>

		<meta charset="utf-8" />
		<meta
			name="viewport"
			content="width=device-width, initial-scale=1" />

		<title>Farmácia Patuleia</title>

		<link
			rel="icon"
			type="image/png"
			href="/images/favicon-color.png" />

		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
			crossorigin="anonymous" />
		<link
			rel="stylesheet"
			href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" />

		<link
			rel="stylesheet"
			href="/styles/main.css" />
	</head>
	<body>
		<nav class="sticky-top navbar navbar-expand-lg navbar-dark bg-primary">
			<div class="container d-flex flex-wrap">
				<a
					class="navbar-brand"
					href="/dashboard"
					>Dashboard</a
				>
				<ul class="nav me-auto">
					<li class="nav-item">
						<a
							href="/services/list"
							class="nav-link px-2 link-light"
							>Serviços</a
						>
					</li>
					<li class="nav-item">
						<a
							href="/sales/list"
							class="nav-link px-2 link-light"
							>Promoções</a
						>
					</li>
					<?php if ($admin): ?>
					<li class="nav-item">
						<a
							href="/users/list"
							class="nav-link px-2 link-light"
							>Utilizadores</a
						>
					</li>
					<?php endif; ?>
				</ul>
					<a
							href="/logout"
							class="btn btn-outline-light"
							>Logout</a
						>

			</div>
		</nav>

		<main>
			<div class="container bd-highlight mt-5">

				<?php foreach ($bag as $message) : ?>
				<div class="mb-4 alert alert-<?= $message['type'] ?>">
					<?= $message['message'] ?>
				</div>
			<?php endforeach; ?>