<form
	class="d-flex mb-4"
	action="/users/list"
	method="get">
	<input
		class="form-control me-2"
		type="search"
		placeholder="Search"
		aria-label="Search"
		name="search"
		value="<?= isset($_GET['search']) ? $_GET['search'] : '' ?>" />
	<button
		class="btn btn-outline-primary"
		type="submit">
		Search
	</button>
</form>

<div class="row d-flex justify-items-between mb-4">
	<?php if (count($users) >
	0) : foreach ($users as $user) : ?>

	<div
		class="col card me-1"
		style="min-width: 15rem; max-width: 20rem">
		<form
			action="/users/list"
			method="post">
			<div class="card-body d-flex flex-column justify-items-start">
				<h5 class="mb-auto"><?= $user->username ?></h5>
				<ul class="list-group mb-3">
					<li class="list-group-item">
						<strong>Nome</strong>
						<?= $user->name ?>
					</li>
					<li class="list-group-item">
						<strong>Administrador</strong>
						<input
							type="hidden"
							name="id"
							value="<?= $user->id ?>" />
						<input
							type="checkbox"
							name="role"
							id="role"
							<?= $user->role === 'admin' ? 'checked' : '' ?>>
					</li>
				</ul>
				<button
					class="btn btn-secondary w-100"
					type="submit">
					Guardar alterações
				</button>
				<a
					href="/users/<?= $user->id ?>/delete"
					class="btn btn-danger w-100"
					id="removeLink"
					onclick="return confirm('Tem a certeza que pretende remover o utilizador?')"
					>Remover</a
				>
			</div>
		</form>
	</div>

	<?php endforeach; else : ?>

	<p>Não há utilizadores criados.</p>

	<?php endif; ?>
</div>

<a
	href="/register"
	class="btn btn-primary mb-5 btn-lg w-100"
	>Criar utilizador</a
>
