<form
	class="d-flex mb-4"
	action="/sales/list"
	method="get">
	<input
		class="form-control me-2"
		type="search"
		placeholder="Search"
		aria-label="Search"
		name="search"
		value="<?= isset($_GET['search']) ? $_GET['search'] : '' ?>" />
	<button
		class="btn btn-outline-primary"
		type="submit">
		Search
	</button>
</form>

<div class="row d-flex justify-items-between mb-4">
	<?php if (count($sales) >
	0) : foreach ($sales as $sale) : ?>

	<div
		class="col card me-1"
		style="min-width: 15rem; max-width:20rem">
		<img
			class="card-img-top p-3"
			src="/<?= $sale->image ?>"
			alt="Card image cap" />

		<div class="card-body d-flex flex-column justify-items-start">
			<h5 class="mb-auto"><?= $sale->name ?></h5>
			<p class="card-text"><?= $sale->description ?></p>
			<a
				href="/sales/detail?id=<?= $sale->id ?>"
				class="btn btn-primary btn-block w-100 mt-auto"
				>Ver mais</a
			>
		</div>
	</div>

	<?php endforeach; else : ?>

	<p>Não há campanhas criadas.</p>

	<?php endif; ?>
</div>

<a
	href="/sales/create"
	class="btn btn-primary mb-5 btn-lg w-100"
	>Adicionar campanha</a
>
